### ISSUE TITLE
Add posibility to replace DEBUG function

### ISSUE THREAD

**Issue by vgoloviznin** [rapid7/le_node#117]
As of 1.5.0 there is DEBUG function that is called on several occasions. 

Is it possible to move this function into options, or optionally turn it on\off?

**Comment by JordanBelford** [comment]
The ability to override the debug function is nice. I think debug logging should also be disabled by default.

**Comment by vgoloviznin** [comment]
@JordanBelford actually, I totally agree. 

I can update my PR if there are no objections :)

**Comment by stopal-r7** [comment]
Disabling it by default sounds good to me.

**Comment by vgoloviznin** [comment]
I've added an empty local debug function, failed to reference the right issue though in the commit, argh

**Comment by stopal-r7** [comment]
This is fixed now. Great job @vgoloviznin!

**Comment by vgoloviznin** [comment]
@stopal-r7  The strange thing is that when I get 1.5.2 through npm it still has old code with DEBUG function

**Comment by StephenHynes7** [comment]
Fixing that now

**Comment by StephenHynes7** [comment]
@vgoloviznin can you check again? Should be correct now. Something spooky was happening with npm.

**Comment by vgoloviznin** [comment]
@StephenHynes7 yep, it worked now!
