### ISSUE TITLE
Event 'connected' is not called.

### ISSUE THREAD

**Issue by gyakushev** [rapid7/le_node#119]
In my snippet below the 'connected' event is never fired, even though the logging works normally. In debugger I have verified that this line is executed: https://github.com/logentries/le_node/blob/master/src/node_modules/logger.js#L199, but `this` here is not the Logger object but some other EventEmitter.

```
var logger = new Logentries(config.logentries);
logger.on('connected', function () {
    logger.lastConnect = new Date();
});
```

**Comment by stopal-r7** [comment]
Yes you're right, nice catch. Trying to figure out where does this event is emitted. "this" in javascript...
