### ISSUE TITLE
1.6.1 release is broken?

### ISSUE THREAD

**Issue by larsthorup** [rapid7/le_node#125]
Fails with `Error: Cannot find module 'le_node'`. Downgrading to 1.6.0 fixes the issue. 
Context: node@6.3.1. npm@3.10.3. Windows 10.

**Comment by zhangsh** [comment]
I got the same issue `Error: Cannot find module 'le_node'`

**Comment by StephenHynes7** [comment]
Weird its appearing for me. Looking into this now

**Comment by StephenHynes7** [comment]
Ah sorry issue is when importing it : ) investigating

**Comment by StephenHynes7** [comment]
Can you try 1.6.2?

**Comment by larsthorup** [comment]
Yes, it works :)
Thx!

**Comment by StephenHynes7** [comment]
Sometimes i hate npm :( Sorry about that guys!
