### ISSUE TITLE
Cannot set inactivityTimeout to 0

### ISSUE THREAD

**Issue by ksullivan** [rapid7/le_node#130]
If you try to set inactivityTimeout to 0 to disable socket timeout, it will set it to the default value.

https://github.com/rapid7/le_node/blob/ca69a94e6b48620442ba0d2b76c3c65a6ab15cef/src/logger.js#L126

**Comment by ksullivan** [comment]
@stopal-r7 Should 

	this.inactivityTimeout = opts.inactivityTimeout || defaults.inactivityTimeout;

be changed to

	this.inactivityTimeout = 'inactivityTimeout' in opts ? opts.inactivityTimeout : defaults.inactivityTimeout;

so that if you pass `inactivityTimeout: 0`, it'll use `0` instead of the default?

**Comment by stopal-r7** [comment]
@ksullivan  yes it can be changed to it, and setting it to 0 will disable timeouts. LGTM along with the change in #131

I wes not thinking supporting disabling timeouts but as it solves your problem, looks good to me.

**Comment by stopal-r7** [comment]
closed as it could be handled with #131
