### ISSUE TITLE
Incorrect timeout

### ISSUE THREAD

**Issue by ksullivan** [rapid7/le_node#131]
Is there a bug on this line?

Should it be using the inactivityTimeout value on the logger instance rather than from the options? 

https://github.com/rapid7/le_node/blob/ca69a94e6b48620442ba0d2b76c3c65a6ab15cef/src/logger.js#L161

**Comment by stopal-r7** [comment]
It checks for opts first if it's falsy(undefined, 0, false etc), then uses the defaults.

**Comment by stopal-r7** [comment]
same as #130 

It checks for opts first if it's falsy(undefined, 0, false etc), then uses the defaults.

**Comment by ksullivan** [comment]
@stopal-r7 Should we change

    this.reconnect = reconnectCore(function initialize() {
      let connection;
      const args = [].slice.call(arguments);
      if (isSecure) {
        connection = tls.connect.apply(tls, args, () => {
          if (!connection.authorized) {
            const errMsg = connection.authorizationError;
            this.emit(new LogentriesError(text.authError(errMsg)));
          } else if (tls && tls.CleartextStream && connection instanceof tls.CleartextStream) {
            this.emit('connect');
          }
        });
      } else {
        connection = net.connect.apply(null, args);
      }
      connection.setTimeout(opts.inactivityTimeout || defaults.inactivityTimeout);
      return connection;
    });

to

    this.reconnect = reconnectCore(function () => {
      let connection;
      const args = [].slice.call(arguments);
      if (isSecure) {
        connection = tls.connect.apply(tls, args, () => { // CHANGE
          if (!connection.authorized) {
            const errMsg = connection.authorizationError;
            this.emit(new LogentriesError(text.authError(errMsg)));
          } else if (tls && tls.CleartextStream && connection instanceof tls.CleartextStream) {
            this.emit('connect');
          }
        });
      } else {
        connection = net.connect.apply(null, args);
      }
      connection.setTimeout(this.inactivityTimeout); // CHANGE
      return connection;
    });

Changes marked with `// CHANGE`.

?

**Comment by stopal-r7** [comment]
@ksullivan yes, we are checking for presence twice. do you want to create a PR this along with the code #130?

**Comment by stopal-r7** [comment]
option for disabling inactivity timeout added as of 1.6.6
