### ISSUE TITLE
Server stopped when multiple bunyanStreams attempt to send error messages at the same time.

### ISSUE THREAD

**Issue by w4-dykim** [rapid7/le_node#133]
**Example**

```javascript
'use strict';

const LeLogger = require('le_node');
const bunyan = require('bunyan');

const log = bunyan.createLogger({
  name: 'bunyan-logger',
  serializers: {
    err: bunyan.stdSerializers.err,
  },
  streams: [],
});

log.addStream(LeLogger.bunyanStream({
  token: 'logentries-token',
  minLevel: 'warn',
  console: true,
}));

log.addStream(LeLogger.bunyanStream({
  token: 'another-logentries-token',
  minLevel: 'error',
  console: true,
}));

// This statement will not kill server.
log.warn({err: 'warn message'}, 'some warn occured');

// But, this statement will kill server.
log.error({err: 'error message'}, 'some error occured');

// This statement will not be executed..
console.log('Is server alive?');
```

When `log.warn()` statement is executed, first bunyanStream sends an error message to Logentries well.
However, when `log.error()` statement is executed, another bunyanStream is spawned and two streams try to send error messages to Logentries at the same time.
At this moment, only the first bunyanStream is able to send a message, and the second bunyanStream fails to send and kill the server.

This occurs after v1.6.2(inclusive)
I think https://github.com/rapid7/le_node/pull/124 has a problem related to this.

**Comment by w4-dykim** [comment]
I had a look at the code and found what causes this problem that I reported.
At this line(https://github.com/rapid7/le_node/blob/master/src/logger.js#L280), modifiedLog is already serialized to a string so they must be done before serializing.
I am not 100% sure since I am not a code owner, it should look like the following code:

```js
if (safeTime) delete modifiedLog[safeTime];
if (safeLevel) delete modifiedLog[safeLevel];

modifiedLog = this._serialize(modifiedLog);
```

Thanks!

**Comment by stopal-r7** [comment]
@w4-dykim I can reproduce this, will be looking into it.
