### ISSUE TITLE
Adding le_node and sending a single log entry from AWS Lambda => 15 sec delay

### ISSUE THREAD

**Issue by vkhazin** [rapid7/le_node#136]
Adding a reference to le_node and calling logger.log(...) will make AWS lambda to delay response by 15 secs.
Removing call to logger.log(...) eliminates the 15 sec delay.
Setting inactivityTimeout to 1 will eliminate the delay, but no entries will show up on logentries.com console.

**Comment by StephenHynes7** [comment]
@vkhazin did you disable the timeout using the disableTimeout param?

**Comment by stopal-r7** [comment]
@vkhazin, you can try to wait for 'buffer drain' event then call closeConnection when you are done with logger. this will minimize the inactivityTimeout related delay. it defaults to 15 seconds that's why you're getting this kind of delay IMHO.

https://github.com/rapid7/le_node#buffer-drain

**Comment by vkhazin** [comment]
@StephenHynes7: Thank you for your suggestion! unfortunately it made matter only worse, from lambda AWS logs:
10:48:29 2016-09-29T14:48:29.916Z	c7d8558a-8653-11e6-9d55-e35330678823	Performance::handler::476.343057 //performance collected inside node.js code - last executable line
10:48:58 END RequestId: c7d8558a-8653-11e6-9d55-e35330678823 //line item collected by AWS lambda infrastructure itself

**Comment by vkhazin** [comment]
Reproduced 15 sec delay using a stand alone node.js app:
const token = 'TOKEN';
const process = require('process');
const logger = new (require('le_node'))({
  token: token
});

process.on('SIGINT', () => {
   logger.notice({ type: 'server', event: 'shutdown' });
   logger.once('buffer drain', () => {
   	console.log('buffer drained');
	logger.closeConnection();
	logger.on('disconnected', () => {
		process.exit();
	});
   });
});

logger.info(new Date().toISOString());
console.log('code has finished');

**Comment by stopal-r7** [comment]
Updated the documentation with regards to the usage of 'buffer drain'.
