### ISSUE TITLE
Webpack build "Path must be a string" error

### ISSUE THREAD

**Issue by taylorstine** [rapid7/le_node#147]
[This line ](https://github.com/rapid7/le_node/blob/master/src/logger.js#L75) is throwing an error for me
`TypeError: Path must be a string. Received undefined`

I'm assuming this has to do with the fact that I'm using webpack, and `module` isn't getting properly compiled?  Am I missing a babel plugin?

**Comment by bathos** [comment]
This is a node library specifically. Webpack’s `require` is not entirely compatible with node’s; while this bit could be worked around, you would still run into other problems that cannot be: the `tls` node standard module cannot be simulated in a browser. There is a separate client for using in a browser context, [le_js](https://github.com/rapid7/le_js).

**Comment by stopal-r7** [comment]
Closing this as clearly explained by @bathos that webpack's require is not compatible with node's.
