### ISSUE TITLE
Question about invalid token

### ISSUE THREAD

**Issue by marco-amoroso** [rapid7/le_node#150]
Hi,

we have been using `le_node` for a while now, it is great, thanks.

We are using in a native app and I have a question about what happens when the token is invalid. My understanding is that it will throw an error and prevent it to load at all. Is it correct?

We are slowly moving away from Logentries so the token will be invalid (I guess). Since we don't have access to old client apps I think this might be a problem.

This is my pseudo-code:

```
require('le_node');
const winston = require('winston');

const logger = new (winston.Logger)({
  transports: [
    new (winston.transports.Console)()
  ]
});

if (env.LOG_ENTRIES_TOKEN) {
  logger.add(winston.transports.Logentries, {
    token: env.LOG_ENTRIES_TOKEN
  });
}
```

**Comment by stopal-r7** [comment]
Hi @marco-amoroso, it should be OK, that would not break anything; however, it's of course better to not to send it at all for best practice.

**Comment by marco-amoroso** [comment]
Thanks for the reply 👍
