### ISSUE TITLE
secure by default?

### ISSUE THREAD

**Issue by markstos** [rapid7/le_node#56]
Why not make 'secure' be the default? It seems like the web is heading towards a secure-by-default design with HTTP/2 being based on SSL.

**Comment by bathos** [comment]
@StephenHynes7  is there any reason we should not change this?

**Comment by wearhere** [comment]
Bump

**Comment by TomTomaso** [comment]
sorry but this careless to not enable by default.

**Comment by stopal-r7** [comment]
It should be secure by default as of  1.4.0
