### ISSUE TITLE
Change log level on winston transporter

### ISSUE THREAD

**Issue by StephenHynes7** [rapid7/le_node#76]
As the title says, may be worth adding a extract in the doc about this.

**Comment by bathos** [comment]
Meaning change the default level? Or something else?

**Comment by StephenHynes7** [comment]
Unless I am being silly and https://github.com/winstonjs/winston#using-logging-levels is what your actually supposed to be doing.

**Comment by bathos** [comment]
It inherits from the winston transport class, and supports everything there -- in theory -- but if you're finding it's not, that wouldn't be a big surprise. I've run into problems with figuring out exactly what winston expects a transport to implement before. For the transport, either 'level' (winston) or 'minLevel' (le_node) should do the same thing.

**Comment by gearoidof-r7** [comment]
I think this can be closed for the moment as our new version fixes it.
