### ISSUE TITLE
Logentries Transport doesn't properly log the Error object

### ISSUE THREAD

**Issue by annanhan** [rapid7/le_node#83]
The error object isn't logged to Logentries when using the transport.

Test case: 
 `var obj;
  try {
    console.log(obj.something.fake);
  }
  catch(err) {
    log.error('null error', err);
  }`

All I see is 'null error' in the log. If I wrap `err` in an object, example: `{exception: err}`, then it works. However, this is not great and not very usable. I looked in the code, and it looks like the check here: https://github.com/logentries/le_node/blob/master/src/node_modules/logger.js#L561 will fail if `meta` is an Error object.

**Comment by bathos** [comment]
Interesting. I wasn't aware of this usage; I was under the impression that when a "meta" object was present, that it would always be something supplied by winston itself rather than the user. FWIW, winston's conventions aside, le_node generally anticipates you logging an error as the entry itself.

**Comment by annanhan** [comment]
`log` is a winston logger in this case and the meta object does eventually get to the Logentries transport from winston

**Comment by rbaindourov** [comment]
Both log.error and log.log('error', err);
Are blowing up for me.



```
/Users/robert/dev/salesforce-sync/job.js:326
    log.error(  selectSQL );
        ^

TypeError: log.error is not a function
    at null.callback (/Users/robert/dev/salesforce-sync/job.js:326:9)
    at Query.handleReadyForQuery (/Users/robert/dev/salesforce-sync/node_modules/pg/lib/query.js:89:10)
    at null.<anonymous> (/Users/robert/dev/salesforce-sync/node_modules/pg/lib/client.js:163:19)
    at emitOne (events.js:82:20)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/Users/robert/dev/salesforce-sync/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
pro:salesforce-sync robert$ ./job.js

events.js:141
      throw er; // Unhandled 'error' event
      ^
LogentriesError: The log method was called with the unknown level "undefined".
    at Logger.log (/Users/robert/dev/salesforce-sync/node_modules/le_node/lib/node_modules/logger.js:291:25)
    at null.callback (/Users/robert/dev/salesforce-sync/job.js:326:9)
    at Query.handleReadyForQuery (/Users/robert/dev/salesforce-sync/node_modules/pg/lib/query.js:89:10)
    at null.<anonymous> (/Users/robert/dev/salesforce-sync/node_modules/pg/lib/client.js:163:19)
    at emitOne (events.js:82:20)
    at emit (events.js:169:7)
    at Socket.<anonymous> (/Users/robert/dev/salesforce-sync/node_modules/pg/lib/connection.js:109:12)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)

```

**Comment by bathos** [comment]
Rob, what's the Winston version / the code where the call is made? AFAIK, the new major version of Winston is currently incompatible with le_node, since they changed some pretty fundamental stuff about how levels work.

**Comment by rbaindourov** [comment]
I'm sorry, today is my first day using this software, and I am not able to find winston under 
```
/Users/robert/dev/salesforce-sync/node_modules/le_node/node_modules
pro:node_modules robert$ ls -al
total 0
drwxr-xr-x   6 robert  staff   204 Dec  7 15:24 .
drwxr-xr-x   7 robert  staff   238 Dec  7 15:24 ..
drwxr-xr-x   9 robert  staff   306 Dec  7 15:24 babel-runtime
drwxr-xr-x   8 robert  staff   272 Dec  7 15:24 codependency
drwxr-xr-x  10 robert  staff   340 Dec  7 15:24 json-stringify-safe
drwxr-xr-x  30 robert  staff  1020 Dec  7 15:24 lodash
pro:node_modules robert$
```

The `package.json` contents for winston entry are 
```
    "winston": {
        "dependencies": {
          "async": {
            "from": "async@>=0.9.0 <0.10.0",
            "resolved": "https://registry.npmjs.org/async/-/async-0.9.2.tgz",
            "version": "0.9.2"
          },
          "colors": {
            "from": "colors@>=1.0.0 <1.1.0",
            "resolved": "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz",
            "version": "1.0.3"
          },
          "cycle": {
            "from": "cycle@>=1.0.0 <1.1.0",
            "resolved": "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz",
            "version": "1.0.3"
          },
          "eyes": {
            "from": "eyes@>=0.1.0 <0.2.0",
            "resolved": "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz",
            "version": "0.1.8"
          },
          "isstream": {
            "from": "isstream@>=0.1.0 <0.2.0",
            "resolved": "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz",
            "version": "0.1.2"
          },
          "pkginfo": {
            "from": "pkginfo@>=0.3.0 <0.4.0",
            "resolved": "https://registry.npmjs.org/pkginfo/-/pkginfo-0.3.0.tgz",
            "version": "0.3.0"
          },
          "stack-trace": {
            "from": "stack-trace@>=0.0.0 <0.1.0",
            "resolved": "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.9.tgz",
            "version": "0.0.9"
          }
        },
        "from": "winston@>=1.0.0 <2.0.0",
        "resolved": "https://registry.npmjs.org/winston/-/winston-1.0.0.tgz",
        "version": "1.0.0"
      }
    },
```

If this is not sufficient, do you have any instructions on what information to include and how to retrieve it?

Thanks

-Robert Baindourov

**Comment by bathos** [comment]
@Robert, I assumed you were using Winston cause that's what this thread was about. If you're using le_node directly, though, the problem may be pretty simple: the method and level name you want is 'err', not 'error', unless you override the defaults.

**Comment by rbaindourov** [comment]
Thank You, Sorry for the confusion.

**Comment by rbaindourov** [comment]
Hello Again,

Here are my findings: 
`log.err` did not work.
`log.log('err', err)` didn't log the error object.

I have to suggest that the team consider creating an alias for `log.log('err'` with `log.error` to maintain parity with `console.error`. It would just be much more intuitive, in my opinion. 

Thanks Again!


-Robert Baindourov

**Comment by bathos** [comment]
@rbaindourov can you show the code where `log` is created?

**Comment by rbaindourov** [comment]
Fixed it!
Error between chair and keyboard!
Thanks so much for your help!

Have a great day!
