### ISSUE TITLE
Update bunyan to 1.5.2

### ISSUE THREAD

**Issue by mrfelton** [rapid7/le_node#91]
Currently installs bunyan 1.3.5, which results in dtrace-provider 0.4.0 being installed, which has some issues installing on Mac OSX (see https://github.com/chrisa/node-dtrace-provider/issues/57 for example). Later versions of bunyan don't have this problem. We should update bunyan to the latest version

**Comment by gearoidof-r7** [comment]
We'll test this locally!

**Comment by stopal-r7** [comment]
this should be fixed as of 1.6.8
